baseURL = 'https://ianmurray.me/lille-bille'
languageCode = 'da-dk'
title = 'Lille Billes Uofficiele Sangbog'
theme = 'paper'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "om"
    name = "Om Siden"
    url = "/om/"
    weight = 10
